# SPOTIFY MOCK
# ------------
%dev.app.mock.spotify.user-id=test-user-a
%test.app.mock.spotify.user-id=test-user-a

# HEALTH CONFIGURATION MASKING
# -----------------------------
app.health.masked-config-keys=app.token-encryption-key,mongodb.connection.string,quarkus.mongodb.connection-string,spotify.client-secret,app.slack.webhook-url
app.health.masked-env-keys=APP_TOKEN_ENCRYPTION_KEY,HTTP_AUTH_ENCRYPTION_KEY,MONGODB_CONNECTION_STRING,SPOTIFY_CLIENT_SECRET,SLACK_WEBHOOK_URL
