# SPOTIFY MOCK
# ------------
%dev.app.mock.spotify.user-id=test-user-a
%test.app.mock.spotify.user-id=test-user-a

# HEALTH CONFIGURATION MASKING
# -----------------------------
app.health.masked-config-keys=app.token-encryption-key,spotify.client-secret
app.health.masked-env-keys=MONGODB_CONNECTION_STRING,SPOTIFY_CLIENT_SECRET,APP_TOKEN_ENCRYPTION_KEY
