# SPOTIFY MOCK
# ------------
%dev.app.mock.spotify.user-id=test-user-a
%test.app.mock.spotify.user-id=test-user-a

# HEALTH CONFIGURATION MASKING
# -----------------------------
app.health.masked-config-keys=app.token-encryption-key,mongodb.connection.string,quarkus.mongodb.connection-string,spotify.client-id,spotify.client-secret
app.health.masked-env-keys=APP_ALLOWED_SPOTIFY_USER_IDS,APP_TOKEN_ENCRYPTION_KEY,HTTP_AUTH_ENCRYPTION_KEY,MONGODB_CONNECTION_STRING,SPOTIFY_CLIENT_ID,SPOTIFY_CLIENT_SECRET
