config:
  warningsAsErrors: true

complexity:
  TooManyFunctions:
    ignorePrivate: true
    active: false

style:
  MaxLineLength:
    maxLineLength: 170
  ReturnCount:
    max: 3

naming:
  MatchingDeclarationName:
    active: false
