# SPOTIFY OAUTH
# -------------
%prod.spotify.client-id=${SPOTIFY_CLIENT_ID}
%dev.spotify.client-id=dev-client-id
%test.spotify.client-id=test-client-id
%prod.spotify.client-secret=${SPOTIFY_CLIENT_SECRET}
%dev.spotify.client-secret=dev-client-secret
%test.spotify.client-secret=test-client-secret
%prod.app.oauth.redirect-uri=${APP_OAUTH_REDIRECT_URI}
%dev.app.oauth.redirect-uri=http://localhost:8080/oauth/callback
%test.app.oauth.redirect-uri=http://localhost:8081/oauth/callback

# SPOTIFY API
# -----------
spotify.accounts.base-url=https://accounts.spotify.com
%dev.spotify.accounts.base-url=http://localhost:8080/mock/spotify
%test.spotify.accounts.base-url=http://localhost:8081/mock/spotify
spotify.api.base-url=https://api.spotify.com
%dev.spotify.api.base-url=http://localhost:8080/mock/spotify
%test.spotify.api.base-url=http://localhost:8081/mock/spotify
spotify.throttle.default-interval-ms=10000
