# DEV SERVICES
# ------------
quarkus.devservices.enabled=true
quarkus.datasource.devservices.show-logs=false

# HEALTH
# ------
%dev.quarkus.smallrye-health.include-problem-details=true

# TESTING
# -------
quarkus.test.integration-test-profile=test

# DOCKER
# ------
quarkus.container-image.builder=docker
quarkus.container-image.build=true
quarkus.container-image.push=false
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=christiangroth/spotify-control
quarkus.container-image.name=quarkus

