# DEV SERVICES
# ------------
quarkus.devservices.enabled=true
quarkus.datasource.devservices.show-logs=false

# HEALTH
# ------
%dev.quarkus.smallrye-health.include-problem-details=true

# TESTING
# -------
quarkus.test.integration-test-profile=test
