name: Java CI/CD with Gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
      - run: ./gradlew --info --stacktrace build
      - run: ./gradlew createModuleGraph
      - run: ./generate-cloc-report.sh
      - run: ./generate-lizard-report.sh
      - name: Upload Kover reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: kover-reports
          path: |
            **/build/reports/kover/
      - name: Upload module dependency reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: modulegraph-reports
          path: build/reports/modulegraph/
      - name: Upload CLOC reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cloc-reports
          path: build/reports/cloc/
      - name: Upload Lizard reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lizard-reports
          path: build/reports/lizard/

  release:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      - uses: gradle/actions/setup-gradle@v5
      - run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Log into registry ghcr.io
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: ./gradlew -info --stacktrace release -x test -x testNative -x koverHtmlReport -x koverVerify
      - run: |
          export DOCKER_TAG=$(docker images ghcr.io/christiangroth/spotify-control/quarkus --format "{{.Tag}} {{.CreatedAt}}" | sort -rk 2 | awk 'NR==1{print $1}')
          echo "DOCKER_TAG=$DOCKER_TAG" >> $GITHUB_ENV
          echo "Computed docker tag for next deployment $DOCKER_TAG"
      - name: Copy docker stack file to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.CONTABO_SSH_HOST }}
          username: ${{ secrets.CONTABO_SSH_USER }}
          key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY }}
          port: 22
          source: "deploy/docker-stack.yml"
          target: "~/spotify-control/"
          strip_components: 1
      - uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKER_STACK: "spotify-control"
          DOCKER_TAG: ${{ env.DOCKER_TAG }}
          HTTP_AUTH_ENCRYPTION_KEY: ${{ secrets.HTTP_AUTH_ENCRYPTION_KEY }}
          TRAEFIK_HTTP_ROUTERS_SPOTIFYCONTROL_RULE: ${{ secrets.TRAEFIK_HTTP_ROUTERS_SPOTIFYCONTROL_RULE }}
          GHCR_PAT: ${{ secrets.GHCR_PAT }}
        with:
          host: ${{ secrets.CONTABO_SSH_HOST }}
          username: ${{ secrets.CONTABO_SSH_USER }}
          key: ${{ secrets.CONTABO_SSH_PRIVATE_KEY }}
          port: 22
          envs: DOCKER_STACK,DOCKER_TAG,HTTP_AUTH_ENCRYPTION_KEY,TRAEFIK_HTTP_ROUTERS_SPOTIFYCONTROL_RULE,GHCR_PAT
          script_stop: true
          script: |
            echo "login to ghcr.io"
            echo $GHCR_PAT | docker login ghcr.io -u christiangroth --password-stdin

            echo "deploying docker stack"
            DOCKER_TAG=$DOCKER_TAG HTTP_AUTH_ENCRYPTION_KEY=$HTTP_AUTH_ENCRYPTION_KEY \
              TRAEFIK_HTTP_ROUTERS_SPOTIFYCONTROL_RULE=$TRAEFIK_HTTP_ROUTERS_SPOTIFYCONTROL_RULE \
              docker stack deploy --detach=false --prune --with-registry-auth --resolve-image changed -c ~/$DOCKER_STACK/docker-stack.yml $DOCKER_STACK
            sleep 5

            echo
            echo "----- ----- -----"
            echo "----- ----- -----"
            echo "----- ----- -----"
            echo

            docker stack ls
            echo
            docker stack services $DOCKER_STACK
            echo
            docker stack ps $DOCKER_STACK
