name: Check Secret Characters

on:
  workflow_dispatch:

jobs:
  check-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Print TEST_SECRET as base64
        env:
          TEST_SECRET: ${{ secrets.MONGODB_CONNECTION_STRING }}
        run: |
          echo "Länge: ${#TEST_SECRET}"
          echo "Base64: $(echo -n "$TEST_SECRET" | base64)"